# ERY: this is an attempt to get git env working and/or use git branch/repo names to isolate the s3 bucket name
#plugins:
#  - serverless-plugin-git-variables

supportDocsTest:
  component: "@sls-next/serverless-component"
  runtime: "nodejs16.x"
  inputs:
    #bucketName: ${git:repository}-${git:branch}
    tag:
      {
        service: "support-docs",
        product: "shared",
        cogs: "0",
        team: "front-end",
        role: "app",
        environment: "tst",
      }
    bucketTags:
      {
        service: "support-docs",
        product: "shared",
        cogs: "0",
        team: "front-end",
        role: "app",
        environment: "tst",
      }
    cloudfront:
      tags:
        service: "support-docs"
        product: "shared"
        cogs: "0"
        team: "front-end"
        role: "app"
        environment: "tst"
